version: 1.12.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
shallow_clone: true
environment:
  VCVER: 14.0
  QTVER: 5.10.1
  QTCOMPILER: msvc2015
  ARCH: x86
  CMakeArgs: "-DLSLAPPS_LabRecorder=1 -DLSLAPPS_Examples=1"
image:
- Visual Studio 2015
- Ubuntu
install:
- cmd: appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
- cmd: 7z x ninja.zip -oC:\projects\deps\ninja > nul
- cmd: set PATH=C:\projects\deps\ninja;%PATH%
- sh: sudo apt update; sudo apt install -y qt5-default ninja
- ninja --version
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio %VCVER%\VC\vcvarsall.bat" %ARCH%
- mkdir build
- cd build
- cmd: cmake -G Ninja -DQt5_DIR=C:/Qt/%QTVER%/%QTCOMPILER%/lib/cmake/Qt5 -DBOOST_ROOT=C:/Libraries/boost_1_67_0 -DCMAKE_BUILD_TYPE=Release %CMakeArgs% ../
- cmake --build . --config Release --target install
artifacts:
- path: build/install
  name: lsl_%ARCH%_%QTCOMPILER%_${APPVEYOR_BUILD_WORKER_IMAGE}_${APPVEYOR_REPO_COMMIT}
